version: "4.34.3"

services:
  postgres:
    image: postgres:13.5
    container_name: products_db

    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - 5432:5432

    volumes:
      - ./postgres:/var/lib/postgresql/data
